		<?php 

			/**
			 * Output footer content generated by WordPress
			 * and any plug-ins -- notes from Chris Maissan
			 */
			wp_footer(); 

		?>


	</div> <!-- #wrapper -->
	<footer>
		© Copyright 2014 | <a href="http://www.lanamilley.com/" target="_blank">lanamilley</a>
	</footer>
</body>
</html>