<!DOCTYPE HTML>
<html>
	<!-- custom fonts -->
	<link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro' rel='stylesheet' type='text/css'>

	<!-- tittle on browser tab -->
	<title><?php if(is_front_page()) { echo bloginfo('name'); } else { wp_title(''); } ?></title>
	<head>
		<?php 

			/**
			 * Output <head> content generated by WordPress
			 * and any plug-ins -- notes from Chris Maissan
			 */
			wp_head(); 

		?>
		<link rel="stylesheet" href="<?php bloginfo('stylesheet_url'); ?>" type="text/css" />		
	</head>
	<body>
		<div id="wrapper">

			<div id="header">
			    <a href="<?php bloginfo('url'); ?>">
			  		<div id="webd252"><img src="http://www.lanamilley.com/webd252/img/banner.png" alt="<?php bloginfo('name'); ?>" /></div>
			    </a>
			     <h1><a href="<?php bloginfo('url'); ?>">" title="<?php bloginfo('name'); ?>">
			         <?php bloginfo('name'); ?></a>
			     </h1>
			</div>

		<nav>
			<?php 

				/**
				 * Output HTML for a menu
				 *
				 * The first paramter is an array of configration
				 * options
				 *
				 * "theme_location" is the ID value used to 
				 * reference the menu location (see functions.php) -- notes from Chris Maissan
				 */
				wp_nav_menu( array(
					'theme_location' => 'main-menu'
				) ); 

			?>
		</nav>